# This is a basic workflow to help you get started with Actions

name: Get Changelog

# Controls when the workflow will run
on:
  schedule: 
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: chrisreddington/rss-parser-action@main
      with:
        branch_prefix: 'gh-changelog'
        feed_url: 'https://github.blog/changelog/feed/'
        script_output: 'issue'
